category:
  cs.AI: Artificial Intelligence ğŸ§ 
  cs.CL: Computation and Language ğŸ’¬
  cs.CV: Computer Vision and Pattern Recognition ğŸ“¸
  cs.LG: Machine Learning ğŸ“Š
  cs.MA: Multiagent Systems ğŸŒ
  cs.RO: Robotics ğŸ¤–

topic:
  LLM:
    keywords:
      - LLM
      - Large Language Model
      - GPT
    filters:
  MLLM:
    keywords:
      - VLM
      - MLM
      - MLLM
      - Multi-Modal Language Model
      - Multimodal Language Model
      - Vision Language Model
    filters:
  Test-Time-Scaling:
    keywords:
      - [LLM, Reasoning]
      - [VLM, Reasoning]
      - [System 2, Thinking]
      - Slow Thinking
      - o1
      - r1
      - test-time-scaling
      - test-time-computing
      - TTS
      - TTC
    filters:
  Embodied_AI:
    keywords:
      - VLA
      - Vision-Language-Action
    filters:
  Diffusion:
    keywords:
      - Diffusion
      - DDPM
      - DDIM
    filters:
  3D_Reconstruction:
    keywords:
      - Reconstruction
      - Nerf
      - Gaussian
    filters:
      - 2D
  3D_Generation:
    keywords:
      - Video Generation
      - Scene Generation
      - Content Generation
    filters:
      - 2D
  Benchmark:
    keywords:
      - Bench
    filters: